export const CATEGORIES = [
  "Administration Studies",
  "Architecture Studies",
  "Art Studies",
  "Aviation",
  "Business Studies",
  "Construction",
  "Cosmetology Studies",
  "Design Studies",
  "Economic Studies",
  "Education",
  "Energy Studies",
  "Engineering Studies",
  "Environmental Studies",
  "Fashion",
  "Food and Beverage Studies",
  "General Studies",
  "Health Care",
  "Humanities Studies",
  "Journalism and Mass Communication",
  "Languages",
  "Law Studies",
  "Life Sciences",
  "Life Skills",
  "Management Studies",
  "Marketing Studies",
  "Natural Sciences",
  "Performing Arts",
  "Professional Studies",
  "Self-Improvement",
  "Social Sciences",
  "Sport and Exercise Studies",
  "Sustainability Studies",
  "Technology Studies",
  "Tourism and Hospitality",
  "Computer Science",
  "Medicine",
  "Mathematics",
];

export const DEGREE_TYPES = [
  "Vocational or Professional",
  "Bachelor",
  "Master",
  "PhD",
  "Certificate",
  "Diploma",
];

export const provinceCityData = {
  "Gyeonggi-do": [
    "Suwon",
    "Seongnam",
    "Anyang",
    "Ansan",
    "Anseong",
    "Yongin",
    "Pyeongtaek",
    "Goyang",
    "Uijeongbu",
    "Icheon",
    "Hwaseong",
    "Namyangju",
  ],
  "Gangwon-do": ["Chuncheon", "Gangneung", "Wonju", "Samcheok"],
  "North Chungcheong": ["Cheongju", "Chungju", "Jecheon"],
  "South Chungcheong": ["Cheonan", "Gongju", "Nonsan", "Dangjin", "Asan"],
  "North Jeolla": ["Jeonju", "Iksan", "Gunsan"],
  "South Jeolla": ["Mokpo", "Yeosu", "Suncheon", "Naju"],
  "North Gyeongsang": ["Gyeongsan", "Andong", "Pohang", "Gumi", "Sangju"],
  "South Gyeongsang": ["Jinju", "Changwon", "Gimhae", "Miryang", "Tongyeong"],
  Jeju: ["Jeju"],
  Seoul: ["Seoul"],
  Busan: ["Busan"],
  Daegu: ["Daegu"],
  Incheon: ["Incheon"],
  Gwangju: ["Gwangju"],
  Daejeon: ["Daejeon"],
  Ulsan: ["Ulsan"],
};
