const universities = [
  {
    id: "snu",
    name: "Seoul National University",
    location: "Seoul, South Korea",
    type: "Public",
    established: "1946",
    accreditation: "Ministry of Education, South Korea",
    website: "https://en.snu.ac.kr",
    email: "admissions@snu.ac.kr",
    phone: "+82 2-880-5114",
    address: "1 Gwanak-ro, Gwanak-gu, Seoul, South Korea",
    description:
      "Seoul National University is Korea’s first national university and one of the most prestigious universities in South Korea, known for its academic excellence and world-class research.",
    images: ["/snu1.jpg", "/snu2.jpg", "/snu3.jpg"],
    rankings: {
      national: 1,
      global: 41,
    },
    statistics: {
      students: 28000,
      internationalStudents: 4000,
      faculty: 2200,
      programs: 80,
      graduationRate: "95%",
      employmentRate: "93%",
    },
    facilities: ["Research Centers", "Library", "Sports Facilities", "Dormitories", "Cafeterias", "Computer Labs"],
    categories: ["Engineering", "Natural Sciences", "Business", "Humanities", "Medicine"],
  },
  {
    id: "pknu",
    name: "Pukyong National University",
    location: "Busan, South Korea",
    type: "Public",
    established: "1996",
    accreditation: "Ministry of Education, South Korea",
    website: "https://www.pknu.ac.kr",
    email: "international@pknu.ac.kr",
    phone: "+82 51-629-5114",
    address: "45 Yongso-ro, Nam-gu, Busan, South Korea",
    description:
      "Pukyong National University is a prominent institution in Busan specializing in marine sciences, engineering, and business, fostering innovation in Korea's southern region.",
    images: ["/pknu1.jpg", "/pknu2.jpg", "/pknu3.jpg"],
    rankings: {
      national: 20,
      global: "-",
    },
    statistics: {
      students: 18000,
      internationalStudents: 2000,
      faculty: 1200,
      programs: 65,
      graduationRate: "88%",
      employmentRate: "85%",
    },
    facilities: ["Marine Research Center", "Library", "Sports Facilities", "Dormitories", "Cafeterias", "IT Labs"],
    categories: ["Engineering", "Marine Science", "Business", "Social Sciences"],
  },
  {
    id: "inha",
    name: "Inha University",
    location: "Incheon, South Korea",
    type: "Private",
    established: "1954",
    accreditation: "Ministry of Education, South Korea",
    website: "https://www.inha.ac.kr",
    email: "admission@inha.ac.kr",
    phone: "+82 32-860-7114",
    address: "100 Inha-ro, Michuhol-gu, Incheon, South Korea",
    description:
      "Inha University is one of South Korea’s leading private universities known for its strength in engineering, business, and logistics, located in the dynamic city of Incheon.",
    images: ["/inha1.jpg", "/inha2.jpg", "/inha3.jpg"],
    rankings: {
      national: 9,
      global: "-",
    },
    statistics: {
      students: 21000,
      internationalStudents: 3200,
      faculty: 1400,
      programs: 70,
      graduationRate: "90%",
      employmentRate: "88%",
    },
    facilities: ["Engineering Labs", "Library", "Sports Facilities", "Dormitories", "Startup Incubator", "Cafeterias"],
    categories: ["Engineering", "Business", "Logistics", "Humanities", "Law"],
  },
  {
    id: "yonsei",
    name: "Yonsei University",
    location: "Seoul, South Korea",
    type: "Private",
    established: "1885",
    accreditation: "Ministry of Education, South Korea",
    website: "https://www.yonsei.ac.kr",
    email: "info@yonsei.ac.kr",
    phone: "+82 2-2123-2114",
    address: "50 Yonsei-ro, Seodaemun-gu, Seoul, South Korea",
    description:
      "Yonsei University is one of the top private universities in Korea, renowned for its liberal arts education, business programs, and medical school.",
    images: ["/yonsei1.jpg", "/yonsei2.jpg", "/yonsei3.jpg"],
    rankings: {
      national: 3,
      global: 73,
    },
    statistics: {
      students: 32000,
      internationalStudents: 4500,
      faculty: 2500,
      programs: 85,
      graduationRate: "94%",
      employmentRate: "90%",
    },
    facilities: ["Medical Center", "Library", "Sports Complex", "Dormitories", "Cafeterias", "Innovation Hubs"],
    categories: ["Engineering", "Business", "Humanities", "Medicine", "Social Sciences"],
  }
];
export default universities;